{% set name = "rilseq" %}
{% set version = "0.76" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RILseq-{{ version }}.tar.gz"
  sha256: 00cc966cbb2c8104b23bde38f2d4fe79bbdae74a11f408ddddd0c04e1a238d1e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - biopython
    - numpy
    - pysam >=0.14.1
    - python
    - scipy
    - bwa >=0.7.12
    - samtools >=1.2

test:
  imports:
    - RILseq

about:
  home: "http://github.com/asafpr/RILseq"
  license: MIT
  license_family: MIT
  summary: "Processing RILSeq experiments results"

extra:
  recipe-maintainers:
    - asafpr
